# If you wish to use vanilla sounds, set this to true
# Keep in mind it disables all custom sounds from place/break/hit etc
disableCustomSounds: false

# [restoreFunctionality]: Restores redstone and vanilla note functionality for noteblocks
# NOTE: This reduces the total amount of custom block slots from 799 to 750
noteBlocks:
  isEnabled: true
  restoreFunctionality: false

tripWires:
  isEnabled: true

# This is experimental and should not be used
# A rework is planned to allow for a much better functionality
leafBlocks:
  isEnabled: false
  disableBurnForBlockyLeaves: false
  disableAllLeafDecay: false
  shouldReserveOnePersistentLeafPerType: true

# You will need to disable these in world-generation if you wanna use it
# It aims to free up all CAVE_VINES except age = 0 and replaces its behaviour with CAVE_VINES_PLANT
caveVineBlocks:
  isEnabled: false
