# If you wish to use vanilla sounds, set this to true
# Keep in mind it disables all custom sounds from place/break/hit etc
disableCustomSounds: false

# Replacement sounds for wood as its entirely removed in resourcepack
noteBlocks:
  isEnabled: true

tripWires:
  isEnabled: true

chorusPlant:
  isEnabled: true

leafBlocks:
  isEnabled: true
  disableBurnForBlockyLeaves: false
  disableAllLeafDecay: false
  shouldReserveOnePersistentLeafPerType: true

# You will need to disable these in world-generation if you wanna use it
# It aims to free up all CAVE_VINES except age = 0 and replaces its behaviour with CAVE_VINES_PLANT
caveVineBlocks:
  isEnabled: false
