# If you wish to use vanilla sounds, set this to true
# Keep in mind it disables all custom sounds from place/break/hit etc
disableCustomSounds: false

# Replacement sounds for wood as its entirely removed in resourcepack
noteBlocks:
  isEnabled: true
  woodPlaceSound: "block.stone.place"
  woodBreakSound: "block.stone.break"
  woodHitSound: "block.stone.hit"
  woodStepSound: "block.stone.step"
  woodFallSound: "block.stone.fall"

tripWires:
  isEnabled: true

chorusPlant:
  isEnabled: true

leafBlocks:
  isEnable: true
  disableBurnForBlockyLeaves: false
  disableAllLeafDecay: false
  shouldReserveOnePersistentLeafPerType: true
