# Replacement sounds for wood as its entirely removed in resourcepack

blockSounds:
  woodPlaceSound: "block.stone.place"
  woodBreakSound: "block.stone.break"
  woodHitSound: "block.stone.hit"
  woodStepSound: "block.stone.step"
  woodFallSound: "block.stone.fall"

leafBlocks:
  disableAllLeafDecay: false
  shouldReserveOnePersistentLeafPerType: true
