name: Blocky
version: ${plugin_version}
main: com.mineinabyss.blocky.BlockyPlugin
api-version: "1.20"
authors: [ boy0000 ]
depend: [ Geary, ProtocolBurrito ]
softdepend: [ Guiy, FastAsyncWorldEdit, MythicMobs ]

commands:
  blocky:
