name: Blocky
version: ${plugin_version}
main: com.mineinabyss.blocky.BlockyPlugin
api-version: 1.19
authors: [ boy0000 ]
depend: [ Geary, Looty ]
softdepend: [ Guiy, FastAsyncWorldEdit, LightAPI, MythicMobs, Breaker ]

commands:
  blocky:
