[versions]
geary = "0.19.113"
gearyaddons = "0.7.45"
looty = "0.8.67"
guiy="0.7.25"
deeperworld="0.6.82"

[libraries]
geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
geary-commons-papermc = { module = "com.mineinabyss:geary-commons-papermc", version.ref = "gearyaddons" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
guiy = { module = "com.mineinabyss:guiy-compose", version.ref = "guiy" }

minecraft-plugin-customblockdata = "com.jeff_media:CustomBlockData:2.1.0"
minecraft-plugin-morepersistentdatatypes = "com.jeff_media:MorePersistentDataTypes:2.3.1"
minecraft-plugin-lightapi = "com.github.BeYkeRYkt:LightAPI:5.3.0-Bukkit"
