[versions]
gearyPaper = "0.23.6"
looty = "0.9.3"
guiy="0.8.0"
deeperworld="0.7.0"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
looty = { module = "com.mineinabyss:looty", version.ref = "looty" }
deeperworld = { module = "com.mineinabyss:deeperworld", version.ref = "deeperworld" }
guiy = { module = "com.mineinabyss:guiy-compose", version.ref = "guiy" }

minecraft-plugin-customblockdata = "com.jeff_media:CustomBlockData:2.2.0"
minecraft-plugin-morepersistentdatatypes = "com.jeff_media:MorePersistentDataTypes:2.3.1"
minecraft-plugin-lightapi = "com.github.BeYkeRYkt:LightAPI:5.3.0-Bukkit"
minecraft-plugin-modelengine = "com.ticxo.modelengine:api:R3.1.3"
minecraft-plugin-protectionlib = "com.github.oraxen:protectionlib:1.2.1"
